name: .NET Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  PROJECT_PATH: "SiemensIXBlazor/SiemensIXBlazor.csproj"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}
      - name: Make build-npm.sh executable
        run: chmod +x .github/build-npm.sh
      - name: Run build-npm.sh
        run: .github/build-npm.sh
      - name: Build
        run: dotnet build --no-restore ${{ env.PROJECT_PATH }} --configuration Release
      - name: Test with the dotnet CLI
        run: dotnet test
