name: .NET Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
   PROJECT_PATH: "SiemensIXBlazor/SiemensIXBlazor.csproj"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }} 
    - name: Build
      run: dotnet build --no-restore ${{ env.PROJECT_PATH }} --configuration Release
